# Generated by Django 6.0.5 on 2026-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=models.URLField(blank=True, help_text='Banner/hero image URL', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_image',
            field=models.URLField(blank=True, help_text='Category image URL', null=True),
        ),
    ]
