# Generated by Django 6.0.5 on 2026-05-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_banner_category_order_address_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Auto-generated 6-digit order number', max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, help_text='6-digit pincode - user enters', max_length=6, null=True),
        ),
    ]
