# Generated by Django 6.0.5 on 2026-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cart_wishlist_user_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('slides', 'Slides'), ('shoes', 'Shoes'), ('sunglass', 'Sunglasses'), ('pants', 'Pants'), ('jacket', 'Jacket'), ('accessories', 'Accessories')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]

