# Generated by Django 6.0.5 on 2026-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_exchange_cashfree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.TextField(blank=True, help_text='Image URL or base64 data URL', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner_image',
            field=models.TextField(blank=True, help_text='Banner/hero image URL or base64 data URL', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_image',
            field=models.TextField(blank=True, help_text='Category image URL or base64 data URL', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, help_text='Image URL or base64 data URL', null=True),
        ),
    ]
