# Generated by Django 6.0.5 on 2026-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.TextField(help_text='Image URL or base64 data URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('slides', 'Slides'), ('shoes', 'Shoes'), ('sunglass', 'Sunglasses'), ('pants', 'Pants'), ('jacket', 'Jacket'), ('accessories', 'Accessories'), ('sarees', 'Sarees')], max_length=50),
        ),
    ]
