# Generated by Django 6.0.5 on 2026-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_banner_image_url_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Multiple product images as JSON array'),
        ),
    ]
