# Generated by Django 6.0.5 on 2026-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
