# Generated by Django 6.0.5 on 2026-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_product_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, help_text='Image URL or base64 data URL', null=True),
        ),
    ]
