# Generated by Django 6.0.5 on 2026-05-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_notification_address_admin_contact'),
        ('api', '0018_order_shipped_at'),
    ]

    operations = [
    ]
