# Generated by Django 5.1 on 2026-05-28 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_product_category_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_temp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_new',
            new_name='category',
        ),
    ]
