# Generated by Django 5.1 on 2026-05-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_product_category_new_product_category_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_temp',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
