# Generated by Django 5.1 on 2026-06-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_product_category_alter_product_category_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_patterns',
            field=models.JSONField(blank=True, default=list, help_text='List of available color patterns for Stone Shirts'),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_designs',
            field=models.JSONField(blank=True, default=list, help_text='List of design image URLs for Stone Shirts'),
        ),
    ]
