# Generated by Django 5.1 on 2026-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_product_color_patterns_product_custom_designs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
